using System.Runtime.InteropServices;
using Avalonia.Input;

namespace KyberAvaloniaRemoteClient;

/// <summary>
/// Maps Avalonia's PhysicalKey enum to platform-specific keycodes expected by
/// KyberSharp's KeyboardKey.MapKeycode(). Avalonia's PhysicalKey values are
/// sequential internal IDs (not USB HID, evdev, or Win32 VK codes), so a
/// lookup table is required per platform.
///
/// On Linux: MapKeycode expects evdev keycodes (linux/input-event-codes.h).
/// On Windows: MapKeycode expects Win32 virtual key codes (VK_*).
/// On macOS: MapKeycode expects macOS virtual key codes (Events.h kVK_*).
/// </summary>
internal static class KeycodeMapper
{
    /// <summary>
    /// Returns the platform-specific keycode for a given Avalonia PhysicalKey,
    /// or 0 if no mapping exists.
    /// </summary>
    public static ushort GetPlatformKeycode(PhysicalKey physicalKey)
    {
        var index = (int)physicalKey;
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            return (uint)index < (uint)EvdevTable.Length ? EvdevTable[index] : (ushort)0;
        }
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            return (uint)index < (uint)Win32VkTable.Length ? Win32VkTable[index] : (ushort)0;
        }
        if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            return (uint)index < (uint)MacOSTable.Length ? MacOSTable[index] : (ushort)0;
        }
        return 0;
    }

    // Indexed by (int)PhysicalKey. Values are Linux evdev keycodes from input-event-codes.h.
    private static readonly ushort[] EvdevTable =
    [
        0,    // None = 0
        41,   // Backquote = 1        → KEY_GRAVE
        43,   // Backslash = 2        → KEY_BACKSLASH
        26,   // BracketLeft = 3      → KEY_LEFTBRACE
        27,   // BracketRight = 4     → KEY_RIGHTBRACE
        51,   // Comma = 5            → KEY_COMMA
        11,   // Digit0 = 6           → KEY_0
        2,    // Digit1 = 7           → KEY_1
        3,    // Digit2 = 8           → KEY_2
        4,    // Digit3 = 9           → KEY_3
        5,    // Digit4 = 10          → KEY_4
        6,    // Digit5 = 11          → KEY_5
        7,    // Digit6 = 12          → KEY_6
        8,    // Digit7 = 13          → KEY_7
        9,    // Digit8 = 14          → KEY_8
        10,   // Digit9 = 15          → KEY_9
        13,   // Equal = 16           → KEY_EQUAL
        86,   // IntlBackslash = 17   → KEY_102ND
        89,   // IntlRo = 18          → KEY_RO
        124,  // IntlYen = 19         → KEY_YEN
        30,   // A = 20               → KEY_A
        48,   // B = 21               → KEY_B
        46,   // C = 22               → KEY_C
        32,   // D = 23               → KEY_D
        18,   // E = 24               → KEY_E
        33,   // F = 25               → KEY_F
        34,   // G = 26               → KEY_G
        35,   // H = 27               → KEY_H
        23,   // I = 28               → KEY_I
        36,   // J = 29               → KEY_J
        37,   // K = 30               → KEY_K
        38,   // L = 31               → KEY_L
        50,   // M = 32               → KEY_M
        49,   // N = 33               → KEY_N
        24,   // O = 34               → KEY_O
        25,   // P = 35               → KEY_P
        16,   // Q = 36               → KEY_Q
        19,   // R = 37               → KEY_R
        31,   // S = 38               → KEY_S
        20,   // T = 39               → KEY_T
        22,   // U = 40               → KEY_U
        47,   // V = 41               → KEY_V
        17,   // W = 42               → KEY_W
        45,   // X = 43               → KEY_X
        21,   // Y = 44               → KEY_Y
        44,   // Z = 45               → KEY_Z
        12,   // Minus = 46           → KEY_MINUS
        52,   // Period = 47          → KEY_DOT
        40,   // Quote = 48           → KEY_APOSTROPHE
        39,   // Semicolon = 49       → KEY_SEMICOLON
        53,   // Slash = 50           → KEY_SLASH
        56,   // AltLeft = 51         → KEY_LEFTALT
        100,  // AltRight = 52        → KEY_RIGHTALT
        14,   // Backspace = 53       → KEY_BACKSPACE
        58,   // CapsLock = 54        → KEY_CAPSLOCK
        127,  // ContextMenu = 55     → KEY_COMPOSE
        29,   // ControlLeft = 56     → KEY_LEFTCTRL
        97,   // ControlRight = 57    → KEY_RIGHTCTRL
        28,   // Enter = 58           → KEY_ENTER
        125,  // MetaLeft = 59        → KEY_LEFTMETA
        126,  // MetaRight = 60       → KEY_RIGHTMETA
        42,   // ShiftLeft = 61       → KEY_LEFTSHIFT
        54,   // ShiftRight = 62      → KEY_RIGHTSHIFT
        57,   // Space = 63           → KEY_SPACE
        15,   // Tab = 64             → KEY_TAB
        92,   // Convert = 65         → KEY_HENKAN
        93,   // KanaMode = 66        → KEY_KATAKANAHIRAGANA
        122,  // Lang1 = 67           → KEY_HANGEUL
        123,  // Lang2 = 68           → KEY_HANJA
        90,   // Lang3 = 69           → KEY_KATAKANA
        91,   // Lang4 = 70           → KEY_HIRAGANA
        85,   // Lang5 = 71           → KEY_ZENKAKUHANKAKU
        94,   // NonConvert = 72      → KEY_MUHENKAN
        111,  // Delete = 73          → KEY_DELETE
        107,  // End = 74             → KEY_END
        138,  // Help = 75            → KEY_HELP
        102,  // Home = 76            → KEY_HOME
        110,  // Insert = 77          → KEY_INSERT
        109,  // PageDown = 78        → KEY_PAGEDOWN
        104,  // PageUp = 79          → KEY_PAGEUP
        108,  // ArrowDown = 80       → KEY_DOWN
        105,  // ArrowLeft = 81       → KEY_LEFT
        106,  // ArrowRight = 82      → KEY_RIGHT
        103,  // ArrowUp = 83         → KEY_UP
        69,   // NumLock = 84         → KEY_NUMLOCK
        82,   // NumPad0 = 85         → KEY_KP0
        79,   // NumPad1 = 86         → KEY_KP1
        80,   // NumPad2 = 87         → KEY_KP2
        81,   // NumPad3 = 88         → KEY_KP3
        75,   // NumPad4 = 89         → KEY_KP4
        76,   // NumPad5 = 90         → KEY_KP5
        77,   // NumPad6 = 91         → KEY_KP6
        71,   // NumPad7 = 92         → KEY_KP7
        72,   // NumPad8 = 93         → KEY_KP8
        73,   // NumPad9 = 94         → KEY_KP9
        78,   // NumPadAdd = 95       → KEY_KPPLUS
        0,    // NumPadClear = 96     → (no standard evdev mapping)
        121,  // NumPadComma = 97     → KEY_KPCOMMA
        83,   // NumPadDecimal = 98   → KEY_KPDOT
        98,   // NumPadDivide = 99    → KEY_KPSLASH
        96,   // NumPadEnter = 100    → KEY_KPENTER
        117,  // NumPadEqual = 101    → KEY_KPEQUAL
        55,   // NumPadMultiply = 102 → KEY_KPASTERISK
        179,  // NumPadParenLeft = 103→ KEY_KPLEFTPAREN
        180,  // NumPadParenRight= 104→ KEY_KPRIGHTPAREN
        74,   // NumPadSubtract = 105 → KEY_KPMINUS
        1,    // Escape = 106         → KEY_ESC
        59,   // F1 = 107             → KEY_F1
        60,   // F2 = 108             → KEY_F2
        61,   // F3 = 109             → KEY_F3
        62,   // F4 = 110             → KEY_F4
        63,   // F5 = 111             → KEY_F5
        64,   // F6 = 112             → KEY_F6
        65,   // F7 = 113             → KEY_F7
        66,   // F8 = 114             → KEY_F8
        67,   // F9 = 115             → KEY_F9
        68,   // F10 = 116            → KEY_F10
        87,   // F11 = 117            → KEY_F11
        88,   // F12 = 118            → KEY_F12
        183,  // F13 = 119            → KEY_F13
        184,  // F14 = 120            → KEY_F14
        185,  // F15 = 121            → KEY_F15
        186,  // F16 = 122            → KEY_F16
        187,  // F17 = 123            → KEY_F17
        188,  // F18 = 124            → KEY_F18
        189,  // F19 = 125            → KEY_F19
        190,  // F20 = 126            → KEY_F20
        191,  // F21 = 127            → KEY_F21
        192,  // F22 = 128            → KEY_F22
        193,  // F23 = 129            → KEY_F23
        194,  // F24 = 130            → KEY_F24
        99,   // PrintScreen = 131    → KEY_SYSRQ
        70,   // ScrollLock = 132     → KEY_SCROLLLOCK
        119,  // Pause = 133          → KEY_PAUSE
        158,  // BrowserBack = 134    → KEY_BACK
        156,  // BrowserFavorites=135 → KEY_BOOKMARKS
        159,  // BrowserForward = 136 → KEY_FORWARD
        172,  // BrowserHome = 137    → KEY_HOMEPAGE
        173,  // BrowserRefresh = 138 → KEY_REFRESH
        217,  // BrowserSearch = 139  → KEY_SEARCH
        128,  // BrowserStop = 140    → KEY_STOP
        161,  // Eject = 141          → KEY_EJECTCD
        148,  // LaunchApp1 = 142     → KEY_PROG1
        140,  // LaunchApp2 = 143     → KEY_CALC
        155,  // LaunchMail = 144     → KEY_MAIL
        164,  // MediaPlayPause = 145 → KEY_PLAYPAUSE
        226,  // MediaSelect = 146    → KEY_MEDIA
        166,  // MediaStop = 147      → KEY_STOPCD
        163,  // MediaTrackNext = 148 → KEY_NEXTSONG
        165,  // MediaTrackPrev = 149 → KEY_PREVIOUSSONG
        116,  // Power = 150          → KEY_POWER
        142,  // Sleep = 151          → KEY_SLEEP
        114,  // AudioVolumeDown = 152→ KEY_VOLUMEDOWN
        113,  // AudioVolumeMute = 153→ KEY_MUTE
        115,  // AudioVolumeUp = 154  → KEY_VOLUMEUP
        143,  // WakeUp = 155         → KEY_WAKEUP
        129,  // Again = 156          → KEY_AGAIN
        133,  // Copy = 157           → KEY_COPY
        137,  // Cut = 158            → KEY_CUT
        136,  // Find = 159           → KEY_FIND
        134,  // Open = 160           → KEY_OPEN
        135,  // Paste = 161          → KEY_PASTE
        130,  // Props = 162          → KEY_PROPS
        0,    // Select = 163         → (no standard evdev mapping)
        131,  // Undo = 164           → KEY_UNDO
    ];

    // Indexed by (int)PhysicalKey. Values are Win32 virtual key codes (VK_*).
    private static readonly ushort[] Win32VkTable =
    [
        0,      // None = 0
        0xC0,   // Backquote = 1        → VK_OEM_3
        0xDC,   // Backslash = 2        → VK_OEM_5
        0xDB,   // BracketLeft = 3      → VK_OEM_4
        0xDD,   // BracketRight = 4     → VK_OEM_6
        0xBC,   // Comma = 5            → VK_OEM_COMMA
        0x30,   // Digit0 = 6           → '0'
        0x31,   // Digit1 = 7           → '1'
        0x32,   // Digit2 = 8           → '2'
        0x33,   // Digit3 = 9           → '3'
        0x34,   // Digit4 = 10          → '4'
        0x35,   // Digit5 = 11          → '5'
        0x36,   // Digit6 = 12          → '6'
        0x37,   // Digit7 = 13          → '7'
        0x38,   // Digit8 = 14          → '8'
        0x39,   // Digit9 = 15          → '9'
        0xBB,   // Equal = 16           → VK_OEM_PLUS
        0xE2,   // IntlBackslash = 17   → VK_OEM_102
        0,      // IntlRo = 18          → (no standard VK)
        0,      // IntlYen = 19         → (no standard VK)
        0x41,   // A = 20               → 'A'
        0x42,   // B = 21               → 'B'
        0x43,   // C = 22               → 'C'
        0x44,   // D = 23               → 'D'
        0x45,   // E = 24               → 'E'
        0x46,   // F = 25               → 'F'
        0x47,   // G = 26               → 'G'
        0x48,   // H = 27               → 'H'
        0x49,   // I = 28               → 'I'
        0x4A,   // J = 29               → 'J'
        0x4B,   // K = 30               → 'K'
        0x4C,   // L = 31               → 'L'
        0x4D,   // M = 32               → 'M'
        0x4E,   // N = 33               → 'N'
        0x4F,   // O = 34               → 'O'
        0x50,   // P = 35               → 'P'
        0x51,   // Q = 36               → 'Q'
        0x52,   // R = 37               → 'R'
        0x53,   // S = 38               → 'S'
        0x54,   // T = 39               → 'T'
        0x55,   // U = 40               → 'U'
        0x56,   // V = 41               → 'V'
        0x57,   // W = 42               → 'W'
        0x58,   // X = 43               → 'X'
        0x59,   // Y = 44               → 'Y'
        0x5A,   // Z = 45               → 'Z'
        0xBD,   // Minus = 46           → VK_OEM_MINUS
        0xBE,   // Period = 47          → VK_OEM_PERIOD
        0xDE,   // Quote = 48           → VK_OEM_7
        0xBA,   // Semicolon = 49       → VK_OEM_1
        0xBF,   // Slash = 50           → VK_OEM_2
        0xA4,   // AltLeft = 51         → VK_LMENU
        0xA5,   // AltRight = 52        → VK_RMENU
        0x08,   // Backspace = 53       → VK_BACK
        0x14,   // CapsLock = 54        → VK_CAPITAL
        0x5D,   // ContextMenu = 55     → VK_APPS
        0xA2,   // ControlLeft = 56     → VK_LCONTROL
        0xA3,   // ControlRight = 57    → VK_RCONTROL
        0x0D,   // Enter = 58           → VK_RETURN
        0x5B,   // MetaLeft = 59        → VK_LWIN
        0x5C,   // MetaRight = 60       → VK_RWIN
        0xA0,   // ShiftLeft = 61       → VK_LSHIFT
        0xA1,   // ShiftRight = 62      → VK_RSHIFT
        0x20,   // Space = 63           → VK_SPACE
        0x09,   // Tab = 64             → VK_TAB
        0x1C,   // Convert = 65         → VK_CONVERT
        0x15,   // KanaMode = 66        → VK_KANA
        0,      // Lang1 = 67           → (no standard VK)
        0x19,   // Lang2 = 68           → VK_HANJA
        0,      // Lang3 = 69           → (no standard VK)
        0,      // Lang4 = 70           → (no standard VK)
        0,      // Lang5 = 71           → (no standard VK)
        0x1D,   // NonConvert = 72      → VK_NONCONVERT
        0x2E,   // Delete = 73          → VK_DELETE
        0x23,   // End = 74             → VK_END
        0x2F,   // Help = 75            → VK_HELP
        0x24,   // Home = 76            → VK_HOME
        0x2D,   // Insert = 77          → VK_INSERT
        0x22,   // PageDown = 78        → VK_NEXT
        0x21,   // PageUp = 79          → VK_PRIOR
        0x28,   // ArrowDown = 80       → VK_DOWN
        0x25,   // ArrowLeft = 81       → VK_LEFT
        0x27,   // ArrowRight = 82      → VK_RIGHT
        0x26,   // ArrowUp = 83         → VK_UP
        0x90,   // NumLock = 84         → VK_NUMLOCK
        0x60,   // NumPad0 = 85         → VK_NUMPAD0
        0x61,   // NumPad1 = 86         → VK_NUMPAD1
        0x62,   // NumPad2 = 87         → VK_NUMPAD2
        0x63,   // NumPad3 = 88         → VK_NUMPAD3
        0x64,   // NumPad4 = 89         → VK_NUMPAD4
        0x65,   // NumPad5 = 90         → VK_NUMPAD5
        0x66,   // NumPad6 = 91         → VK_NUMPAD6
        0x67,   // NumPad7 = 92         → VK_NUMPAD7
        0x68,   // NumPad8 = 93         → VK_NUMPAD8
        0x69,   // NumPad9 = 94         → VK_NUMPAD9
        0x6B,   // NumPadAdd = 95       → VK_ADD
        0x0C,   // NumPadClear = 96     → VK_CLEAR
        0x6C,   // NumPadComma = 97     → VK_SEPARATOR
        0x6E,   // NumPadDecimal = 98   → VK_DECIMAL
        0x6F,   // NumPadDivide = 99    → VK_DIVIDE
        0x0D,   // NumPadEnter = 100    → VK_RETURN
        0,      // NumPadEqual = 101    → (no standard VK)
        0x6A,   // NumPadMultiply = 102 → VK_MULTIPLY
        0,      // NumPadParenLeft = 103→ (no standard VK)
        0,      // NumPadParenRight=104 → (no standard VK)
        0x6D,   // NumPadSubtract = 105 → VK_SUBTRACT
        0x1B,   // Escape = 106         → VK_ESCAPE
        0x70,   // F1 = 107             → VK_F1
        0x71,   // F2 = 108             → VK_F2
        0x72,   // F3 = 109             → VK_F3
        0x73,   // F4 = 110             → VK_F4
        0x74,   // F5 = 111             → VK_F5
        0x75,   // F6 = 112             → VK_F6
        0x76,   // F7 = 113             → VK_F7
        0x77,   // F8 = 114             → VK_F8
        0x78,   // F9 = 115             → VK_F9
        0x79,   // F10 = 116            → VK_F10
        0x7A,   // F11 = 117            → VK_F11
        0x7B,   // F12 = 118            → VK_F12
        0x7C,   // F13 = 119            → VK_F13
        0x7D,   // F14 = 120            → VK_F14
        0x7E,   // F15 = 121            → VK_F15
        0x7F,   // F16 = 122            → VK_F16
        0x80,   // F17 = 123            → VK_F17
        0x81,   // F18 = 124            → VK_F18
        0x82,   // F19 = 125            → VK_F19
        0x83,   // F20 = 126            → VK_F20
        0x84,   // F21 = 127            → VK_F21
        0x85,   // F22 = 128            → VK_F22
        0x86,   // F23 = 129            → VK_F23
        0x87,   // F24 = 130            → VK_F24
        0x2C,   // PrintScreen = 131    → VK_SNAPSHOT
        0x91,   // ScrollLock = 132     → VK_SCROLL
        0x13,   // Pause = 133          → VK_PAUSE
        0xA6,   // BrowserBack = 134    → VK_BROWSER_BACK
        0xAB,   // BrowserFavorites=135 → VK_BROWSER_FAVORITES
        0xA7,   // BrowserForward = 136 → VK_BROWSER_FORWARD
        0xAC,   // BrowserHome = 137    → VK_BROWSER_HOME
        0xA8,   // BrowserRefresh = 138 → VK_BROWSER_REFRESH
        0xAA,   // BrowserSearch = 139  → VK_BROWSER_SEARCH
        0xA9,   // BrowserStop = 140    → VK_BROWSER_STOP
        0,      // Eject = 141          → (no standard VK)
        0xB6,   // LaunchApp1 = 142     → VK_LAUNCH_APP1
        0xB7,   // LaunchApp2 = 143     → VK_LAUNCH_APP2
        0xB4,   // LaunchMail = 144     → VK_LAUNCH_MAIL
        0xB3,   // MediaPlayPause = 145 → VK_MEDIA_PLAY_PAUSE
        0xB5,   // MediaSelect = 146    → VK_LAUNCH_MEDIA_SELECT
        0xB2,   // MediaStop = 147      → VK_MEDIA_STOP
        0xB0,   // MediaTrackNext = 148 → VK_MEDIA_NEXT_TRACK
        0xB1,   // MediaTrackPrev = 149 → VK_MEDIA_PREV_TRACK
        0,      // Power = 150          → (no standard VK)
        0x5F,   // Sleep = 151          → VK_SLEEP
        0xAE,   // AudioVolumeDown = 152→ VK_VOLUME_DOWN
        0xAD,   // AudioVolumeMute = 153→ VK_VOLUME_MUTE
        0xAF,   // AudioVolumeUp = 154  → VK_VOLUME_UP
        0,      // WakeUp = 155         → (no standard VK)
        0,      // Again = 156          → (no standard VK)
        0,      // Copy = 157           → (no standard VK)
        0,      // Cut = 158            → (no standard VK)
        0,      // Find = 159           → (no standard VK)
        0,      // Open = 160           → (no standard VK)
        0,      // Paste = 161          → (no standard VK)
        0,      // Props = 162          → (no standard VK)
        0,      // Select = 163         → (no standard VK)
        0,      // Undo = 164           → (no standard VK)
    ];

    // Indexed by (int)PhysicalKey. Values are macOS virtual key codes (kVK_* from Events.h).
    // The Kyber server expects these when the client runs on macOS. The server translates
    // them to the appropriate scancodes for the host OS.
    private static readonly ushort[] MacOSTable =
    [
        0,      // None = 0
        0x32,   // Backquote = 1        → kVK_ANSI_Grave
        0x2A,   // Backslash = 2        → kVK_ANSI_Backslash
        0x21,   // BracketLeft = 3      → kVK_ANSI_LeftBracket
        0x1E,   // BracketRight = 4     → kVK_ANSI_RightBracket
        0x2B,   // Comma = 5            → kVK_ANSI_Comma
        0x1D,   // Digit0 = 6           → kVK_ANSI_0
        0x12,   // Digit1 = 7           → kVK_ANSI_1
        0x13,   // Digit2 = 8           → kVK_ANSI_2
        0x14,   // Digit3 = 9           → kVK_ANSI_3
        0x15,   // Digit4 = 10          → kVK_ANSI_4
        0x17,   // Digit5 = 11          → kVK_ANSI_5
        0x16,   // Digit6 = 12          → kVK_ANSI_6
        0x1A,   // Digit7 = 13          → kVK_ANSI_7
        0x1C,   // Digit8 = 14          → kVK_ANSI_8
        0x19,   // Digit9 = 15          → kVK_ANSI_9
        0x18,   // Equal = 16           → kVK_ANSI_Equal
        0x0A,   // IntlBackslash = 17   → kVK_ISO_Section
        0,      // IntlRo = 18          → (no standard macOS VK)
        0x5D,   // IntlYen = 19         → kVK_JIS_Yen
        0x00,   // A = 20               → kVK_ANSI_A
        0x0B,   // B = 21               → kVK_ANSI_B
        0x08,   // C = 22               → kVK_ANSI_C
        0x02,   // D = 23               → kVK_ANSI_D
        0x0E,   // E = 24               → kVK_ANSI_E
        0x03,   // F = 25               → kVK_ANSI_F
        0x05,   // G = 26               → kVK_ANSI_G
        0x04,   // H = 27               → kVK_ANSI_H
        0x22,   // I = 28               → kVK_ANSI_I
        0x26,   // J = 29               → kVK_ANSI_J
        0x28,   // K = 30               → kVK_ANSI_K
        0x25,   // L = 31               → kVK_ANSI_L
        0x2E,   // M = 32               → kVK_ANSI_M
        0x2D,   // N = 33               → kVK_ANSI_N
        0x1F,   // O = 34               → kVK_ANSI_O
        0x23,   // P = 35               → kVK_ANSI_P
        0x0C,   // Q = 36               → kVK_ANSI_Q
        0x0F,   // R = 37               → kVK_ANSI_R
        0x01,   // S = 38               → kVK_ANSI_S
        0x11,   // T = 39               → kVK_ANSI_T
        0x20,   // U = 40               → kVK_ANSI_U
        0x09,   // V = 41               → kVK_ANSI_V
        0x0D,   // W = 42               → kVK_ANSI_W
        0x07,   // X = 43               → kVK_ANSI_X
        0x10,   // Y = 44               → kVK_ANSI_Y
        0x06,   // Z = 45               → kVK_ANSI_Z
        0x1B,   // Minus = 46           → kVK_ANSI_Minus
        0x2F,   // Period = 47          → kVK_ANSI_Period
        0x27,   // Quote = 48           → kVK_ANSI_Quote
        0x29,   // Semicolon = 49       → kVK_ANSI_Semicolon
        0x2C,   // Slash = 50           → kVK_ANSI_Slash
        0x3A,   // AltLeft = 51         → kVK_Option
        0x3D,   // AltRight = 52        → kVK_RightOption
        0x33,   // Backspace = 53       → kVK_Delete
        0x39,   // CapsLock = 54        → kVK_CapsLock
        0x6E,   // ContextMenu = 55     → (no standard, use 0x6E)
        0x3B,   // ControlLeft = 56     → kVK_Control
        0x3E,   // ControlRight = 57    → kVK_RightControl
        0x24,   // Enter = 58           → kVK_Return
        0x37,   // MetaLeft = 59        → kVK_Command
        0x36,   // MetaRight = 60       → kVK_RightCommand
        0x38,   // ShiftLeft = 61       → kVK_Shift
        0x3C,   // ShiftRight = 62      → kVK_RightShift
        0x31,   // Space = 63           → kVK_Space
        0x30,   // Tab = 64             → kVK_Tab
        0,      // Convert = 65         → (no standard macOS VK)
        0,      // KanaMode = 66        → (no standard macOS VK)
        0,      // Lang1 = 67           → (no standard macOS VK)
        0,      // Lang2 = 68           → (no standard macOS VK)
        0,      // Lang3 = 69           → (no standard macOS VK)
        0,      // Lang4 = 70           → (no standard macOS VK)
        0,      // Lang5 = 71           → (no standard macOS VK)
        0,      // NonConvert = 72      → (no standard macOS VK)
        0x75,   // Delete = 73          → kVK_ForwardDelete
        0x77,   // End = 74             → kVK_End
        0x72,   // Help = 75            → kVK_Help
        0x73,   // Home = 76            → kVK_Home
        0x72,   // Insert = 77          → kVK_Help (Mac uses Help key in Insert position)
        0x79,   // PageDown = 78        → kVK_PageDown
        0x74,   // PageUp = 79          → kVK_PageUp
        0x7D,   // ArrowDown = 80       → kVK_DownArrow
        0x7B,   // ArrowLeft = 81       → kVK_LeftArrow
        0x7C,   // ArrowRight = 82      → kVK_RightArrow
        0x7E,   // ArrowUp = 83         → kVK_UpArrow
        0x47,   // NumLock = 84         → kVK_ANSI_KeypadClear (Mac uses Clear instead of NumLock)
        0x52,   // NumPad0 = 85         → kVK_ANSI_Keypad0
        0x53,   // NumPad1 = 86         → kVK_ANSI_Keypad1
        0x54,   // NumPad2 = 87         → kVK_ANSI_Keypad2
        0x55,   // NumPad3 = 88         → kVK_ANSI_Keypad3
        0x56,   // NumPad4 = 89         → kVK_ANSI_Keypad4
        0x57,   // NumPad5 = 90         → kVK_ANSI_Keypad5
        0x58,   // NumPad6 = 91         → kVK_ANSI_Keypad6
        0x59,   // NumPad7 = 92         → kVK_ANSI_Keypad7
        0x5B,   // NumPad8 = 93         → kVK_ANSI_Keypad8
        0x5C,   // NumPad9 = 94         → kVK_ANSI_Keypad9
        0x45,   // NumPadAdd = 95       → kVK_ANSI_KeypadPlus
        0x47,   // NumPadClear = 96     → kVK_ANSI_KeypadClear
        0,      // NumPadComma = 97     → (no standard macOS VK)
        0x41,   // NumPadDecimal = 98   → kVK_ANSI_KeypadDecimal
        0x4B,   // NumPadDivide = 99    → kVK_ANSI_KeypadDivide
        0x4C,   // NumPadEnter = 100    → kVK_ANSI_KeypadEnter
        0x51,   // NumPadEqual = 101    → kVK_ANSI_KeypadEquals
        0x43,   // NumPadMultiply = 102 → kVK_ANSI_KeypadMultiply
        0,      // NumPadParenLeft = 103→ (no standard macOS VK)
        0,      // NumPadParenRight=104 → (no standard macOS VK)
        0x4E,   // NumPadSubtract = 105 → kVK_ANSI_KeypadMinus
        0x35,   // Escape = 106         → kVK_Escape
        0x7A,   // F1 = 107             → kVK_F1
        0x78,   // F2 = 108             → kVK_F2
        0x63,   // F3 = 109             → kVK_F3
        0x76,   // F4 = 110             → kVK_F4
        0x60,   // F5 = 111             → kVK_F5
        0x61,   // F6 = 112             → kVK_F6
        0x62,   // F7 = 113             → kVK_F7
        0x64,   // F8 = 114             → kVK_F8
        0x65,   // F9 = 115             → kVK_F9
        0x6D,   // F10 = 116            → kVK_F10
        0x67,   // F11 = 117            → kVK_F11
        0x6F,   // F12 = 118            → kVK_F12
        0x69,   // F13 = 119            → kVK_F13
        0x6B,   // F14 = 120            → kVK_F14
        0x71,   // F15 = 121            → kVK_F15
        0x6A,   // F16 = 122            → kVK_F16
        0x40,   // F17 = 123            → kVK_F17
        0x4F,   // F18 = 124            → kVK_F18
        0x50,   // F19 = 125            → kVK_F19
        0x5A,   // F20 = 126            → kVK_F20
        0,      // F21 = 127            → (no macOS VK)
        0,      // F22 = 128            → (no macOS VK)
        0,      // F23 = 129            → (no macOS VK)
        0,      // F24 = 130            → (no macOS VK)
        0,      // PrintScreen = 131    → (no macOS VK, Mac uses Cmd+Shift+3/4)
        0,      // ScrollLock = 132     → (no macOS VK)
        0,      // Pause = 133          → (no macOS VK)
        0,      // BrowserBack = 134    → (no macOS VK)
        0,      // BrowserFavorites=135 → (no macOS VK)
        0,      // BrowserForward = 136 → (no macOS VK)
        0,      // BrowserHome = 137    → (no macOS VK)
        0,      // BrowserRefresh = 138 → (no macOS VK)
        0,      // BrowserSearch = 139  → (no macOS VK)
        0,      // BrowserStop = 140    → (no macOS VK)
        0,      // Eject = 141          → (no macOS VK)
        0,      // LaunchApp1 = 142     → (no macOS VK)
        0,      // LaunchApp2 = 143     → (no macOS VK)
        0,      // LaunchMail = 144     → (no macOS VK)
        0,      // MediaPlayPause = 145 → (no macOS VK)
        0,      // MediaSelect = 146    → (no macOS VK)
        0,      // MediaStop = 147      → (no macOS VK)
        0,      // MediaTrackNext = 148 → (no macOS VK)
        0,      // MediaTrackPrev = 149 → (no macOS VK)
        0,      // Power = 150          → (no macOS VK)
        0,      // Sleep = 151          → (no macOS VK)
        0,      // AudioVolumeDown = 152→ (no macOS VK)
        0,      // AudioVolumeMute = 153→ (no macOS VK)
        0,      // AudioVolumeUp = 154  → (no macOS VK)
        0,      // WakeUp = 155         → (no macOS VK)
        0,      // Again = 156          → (no macOS VK)
        0,      // Copy = 157           → (no macOS VK)
        0,      // Cut = 158            → (no macOS VK)
        0,      // Find = 159           → (no macOS VK)
        0,      // Open = 160           → (no macOS VK)
        0,      // Paste = 161          → (no macOS VK)
        0,      // Props = 162          → (no macOS VK)
        0,      // Select = 163         → (no macOS VK)
        0,      // Undo = 164           → (no macOS VK)
    ];
}
